src/Entity/SweatShirts.php
<?php

namespace App\Entity;

use App\Repository\SweatShirtsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SweatShirtsRepository::class)]
class SweatShirts
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $price = null;

    #[ORM\Column]
    private ?int $xs_stock = null;

    #[ORM\Column]
    private ?int $s_stock = null;

    #[ORM\Column]
    private ?int $m_stock = null;

    #[ORM\Column]
    private ?int $l_stock = null;

    #[ORM\Column]
    private ?int $xl_stock = null;

    #[ORM\Column(length: 255)]
    private ?string $img = null;

    #[ORM\Column(type: 'boolean')]
    private bool $featured = false;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price !== null ? (float) $this->price : null;
    }

    public function setPrice(float $price): static
    {
        $this->price = number_format($price, 2, '.', '');
    
        return $this;
    }

    public function getXsStock(): ?int
    {
        return $this->xs_stock;
    }

    public function setXsStock(int $xs_stock): static
    {
        $this->xs_stock = $xs_stock;

        return $this;
    }

    public function getSStock(): ?int
    {
        return $this->s_stock;
    }

    public function setSStock(int $s_stock): static
    {
        $this->s_stock = $s_stock;

        return $this;
    }

    public function getMStock(): ?int
    {
        return $this->m_stock;
    }

    public function setMStock(int $m_stock): static
    {
        $this->m_stock = $m_stock;

        return $this;
    }

    public function getLStock(): ?int
    {
        return $this->l_stock;
    }

    public function setLStock(int $l_stock): static
    {
        $this->l_stock = $l_stock;

        return $this;
    }

    public function getXlStock(): ?int
    {
        return $this->xl_stock;
    }

    public function setXlStock(int $xl_stock): static
    {
        $this->xl_stock = $xl_stock;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(string $img): static
    {
        $this->img = $img;

        return $this;
    }

    public function isFeatured(): bool
    {
        return $this->featured;
    }

    public function setFeatured(bool $featured): self
    {
        $this->featured = $featured;
        return $this;
    }

}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\SweatShirts;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

class ProductController extends AbstractController
{
    #[Route('/product/{id}', name: 'app_product')]
    #[IsGranted('ROLE_USER')]
    public function index(SweatShirts $sweatShirts): Response
    {
        return $this->render('product/index.html.twig', [
            'controller_name' => 'ProductController',
            'product' => $sweatShirts,
        ]);
    }
}

src/Controller/ProductsController.php
<?php

namespace App\Controller;

use App\Repository\SweatShirtsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

class ProductsController extends AbstractController
{
    #[Route('/products', name: 'app_products')]
    #[IsGranted('ROLE_USER')]
    public function index(SweatShirtsRepository $sweatShirtsRepository): Response
    {
        $products = $sweatShirtsRepository->findAllProducts();


        return $this->render('products/index.html.twig', [
            'controller_name' => 'ProductsController',
            'products' => $products,
        ]);
    }
}

templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}product{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('assets/styles/product.css') }}">
{% endblock %}

{% block body %}
    <main class="d-flex flex-column align-items-center justify-content-center flex-grow-1">
    {% for message in app.flashes('error') %}
        {% if product.xsStock + product.sStock + product.mStock + product.lStock + product.xlStock == 0 %}
                            <div class="alert alert-danger" role="alert">
                                Ce produit est en rupture de stock.
                            </div>      
        {% else %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
        {% endif %}
    {% endfor %}
    <section class="product_container">
        <div class="product d-flex flex-row gap-5 w-100">
                <img class="product_img" src="{{ asset('assets/images/'~ product.img) }}" alt="">
                <div class="d-flex flex-column align-items-end justify-content-around w-100">
                    <div class="d-flex justify-content-between align-items-start  w-100">    
                        <div class="d-flex flex-column justify-content-between w-100">
                            <p>{{ product.name }}</p>
                            <p>{{product.price}} €</p>
                        </div>
                        {% if product.xsStock + product.sStock + product.mStock + product.lStock + product.xlStock == 0 %}
                            <p class="text-danger">En rupture de stock.</p>
                        {% else %}
                        <select name="sizes" id="sizes">
                            <option value="" disabled selected>Taille</option>
                            {% if product.xsStock > 0 %}
                                <option value="xs">XS</option>
                            {% endif %}
                            
                            {% if product.sStock > 0 %}
                                <option value="s">S</option>
                            {% endif %}

                            {% if product.mStock > 0 %}
                                <option value="m">m</option>
                            {% endif %}

                            {% if product.lStock > 0 %}
                                <option value="l">L</option>
                            {% endif %}

                            {% if product.xlStock > 0 %}
                                <option value="xl">XL</option>
                            {% endif %}
                        </select>

                        {% endif %}
                    </div>

                    <a href="{{ path('cart_add', { id: product.id }) }}" id="addToCartBtn" class="product_btn">AJOUTER AU PANIER</a>
                </div>
            </div>
    </section>
</main>

<script>
    document.getElementById('sizes').addEventListener('change', function(){
        const selectedSize = this.value;

        const addTocartBtn = document.getElementById('addToCartBtn');
        addToCartBtn.href = "{{ path('cart_add', { id: product.id }) }}" + "?size=" + selectedSize;
    })
</script>
{% endblock %}